---

- hosts: all
  become: true
  pre_tasks: 

  - name: Updating and Upgrading the OS
    community.general.zypper:
      name: "*"
      state: latest
      update_cache: true

- hosts: controller_node 
  become: true
  roles:
    - ntp
    - packages
    - database
    - message_queue
    - memcached
    - etcd
