---

- name: Installing OpenStack packages on Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  loop:
      - python3-openstackclient
      - python3-novaclient
      - python3-neutronclient
      - python3-glanceclient
      - python3-heatclient


